### ISSUE TITLE
초기화 함수 initialize 관련

### ISSUE THREAD

**Issue by hkhpub** [koalanlp/python-support#2]
안녕하세요 좋은 툴을 만들어주셔서 감사합니다.

다름이 아니라 초기화 함수 initialize와 관련하여 궁금한게 있습니다.
```python
# 초기화 합니다.
initialize(packages=[API.KKMA, API.EUNJEON], version="1.9.2", java_options="-Xmx4g -Dfile.encoding=utf-8")
```
이 함수를 실행할 때마다 pom repo 검색하고 jar파일을 다운 받던데 
혹시 이 과정을 skip할 수 있는 방법이 있을까요?

답변 부탁드려요.

감사합니다.

**Comment by hkhpub** [comment]
제가 실수했네요
매번 다운로드 받는것 아니네요!

**Comment by nearbydelta** [comment]
안녕하세요.

현재 구현 상으로는 로컬 디렉터리에 캐싱하도록 되어 있습니다. [initialize.py 125행](https://github.com/koalanlp/py-koalanlp/blob/master/koalanlp/api/initialize.py#L125)

혹시 다음 폴더가 생성되지 않거나 권한이 없는 것은 아닌지 확인 부탁드립니다.
- `~/.m2/repository`
- `~/.ivy2/cache`

아니라면 로그를 혹시 올려주실 수 있을까요?

**Comment by nearbydelta** [comment]
로컬 저장소 탐색 과정에서 이미 설치된 파일이 존재하는지 query하는 부분이 누락되어 있었습니다.
누락된 부분을 수정하고 조치하였는데, 새 버전에서는 이 문제가 해결될 것 같습니다. 새 버전이 올라가면 알려드리겠습니다.

**Comment by nearbydelta** [comment]
PyPi 패키지 2.1.3부터 문제를 일부 해결하였습니다. 비슷한 문제가 발생하면 다시 열어주세요.
